/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import Modelo.Conectar;
import javax.swing.JOptionPane;
import Modelo.Tienda;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Agregar extends javax.swing.JDialog {
    /**
     * Creates new form Agregar
     */
    Tienda t=new Tienda();
    PreparedStatement stmt=null;
    public Agregar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAgregar1 = new javax.swing.JButton();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jTextFieldStock = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonAgregar1.setText("Agregar");
        jButtonAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar1ActionPerformed(evt);
            }
        });

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Acción", "Aventura", "Deporte", "Mesa", "Habilidad", "Carreras", "Estrategia", "Disparos" }));

        jTextFieldPrecio.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextFieldPrecioInputMethodTextChanged(evt);
            }
        });
        jTextFieldPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel13.setText("Registrar Juego");

        jLabel2.setText("ID:");

        jLabel1.setText("Nombre:");

        jLabel3.setText("Precio:");

        jLabel4.setText("Stock:");

        jLabel5.setText("Categoria:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jButtonAgregar1))
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jTextFieldStock)
                            .addComponent(jTextFieldPrecio)
                            .addComponent(jTextFieldID)
                            .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAgregar1)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar1ActionPerformed
        /*try {
            Juego j=new Juego();
            boolean a=true;
            if ("".equals(this.jTextFieldID.getText())){
                JOptionPane.showMessageDialog(null, "Ingrese el ID del juego\nVuelva a Intentarlo...");
                a=false;
                this.jTextFieldID.setText("");
            }
            if("".equals(this.jTextFieldNombre.getText())) {
                JOptionPane.showMessageDialog(null, "Ingrese el Nombre del juego\nVuelva a Intentarlo...");
                a=false;
                this.jTextFieldNombre.setText("");
            }
            if("".equals(this.jTextFieldPrecio.getText())) {
                JOptionPane.showMessageDialog(null, "Ingrese el Precio del juego\nVuelva a Intentarlo...");
                a=false;
                this.jTextFieldPrecio.setText("");
            }
            if ("".equals(this.jTextFieldStock.getText())){
                JOptionPane.showMessageDialog(null, "Ingrese el Stock del juego\nVuelva a Intentarlo...");
                a=false;
                this.jTextFieldStock.setText("");
            }
            if("Seleccione una opcion".equals(this.jComboBoxCategoria.getSelectedItem())) {
                JOptionPane.showMessageDialog(null, "Ingrese la Categoria del juego\nVuelva a Intentarlo...");
                a=false;
            }
            if (a==true) {
                j.setId(Integer.parseInt(this.jTextFieldID.getText()));
                j.setNombre(this.jTextFieldNombre.getText());
                j.setCategoria((String)this.jComboBoxCategoria.getSelectedItem());
                j.setPrecio(String.valueOf(this.jTextFieldPrecio.getText()));
                j.setStock(Integer.parseInt(this.jTextFieldStock.getText()));
                t.agregar(j);
                this.jTextFieldID.setText("");
                this.jTextFieldNombre.setText("");
                this.jTextFieldPrecio.setText("");
                this.jTextFieldStock.setText("");
                this.jComboBoxCategoria.setSelectedIndex(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro Inválido\nVuelva a Intentarlo...");
        }*/
        try {
            
            Conectar cl=new Conectar();
            Connection reg=cl.getConnection();
            String nombre,categoria,sql;
            int id,precio,stock;
            boolean a=true;
            if ("".equals(this.jTextFieldID.getText())){
                JOptionPane.showMessageDialog(null, "Ingrese el ID del juego\nVuelva a Intentarlo...");
                a=false;
                this.jTextFieldID.setText("");
            }
            if("".equals(this.jTextFieldNombre.getText())) {
                JOptionPane.showMessageDialog(null, "Ingrese el Nombre del juego\nVuelva a Intentarlo...");
                a=false;
                this.jTextFieldNombre.setText("");
            }
            if("".equals(this.jTextFieldPrecio.getText())) {
                JOptionPane.showMessageDialog(null, "Ingrese el Precio del juego\nVuelva a Intentarlo...");
                a=false;
                this.jTextFieldPrecio.setText("");
            }
            if ("".equals(this.jTextFieldStock.getText())){
                JOptionPane.showMessageDialog(null, "Ingrese el Stock del juego\nVuelva a Intentarlo...");
                a=false;
                this.jTextFieldStock.setText("");
            }
            if("Seleccione una opcion".equals(this.jComboBoxCategoria.getSelectedItem())) {
                JOptionPane.showMessageDialog(null, "Ingrese la Categoria del juego\nVuelva a Intentarlo...");
                a=false;
            }
            if (a==true) {
                id=Integer.parseInt(jTextFieldID.getText());
                nombre=jTextFieldNombre.getText();
                precio=Integer.parseInt(jTextFieldPrecio.getText());
                stock=Integer.parseInt(jTextFieldStock.getText());
                categoria=(String)jComboBoxCategoria.getSelectedItem();
                sql="INSERT INTO tabla_juego(id,nombre_jue,precio_jue,categoria_jue,stock_jue)VALUES(?,?,?,?,?)";
                try {
                    PreparedStatement pst=reg.prepareStatement(sql);
                    try {
                        pst.setInt(1, id);
                        pst.setString(2, nombre);
                        pst.setInt(3, precio);
                        pst.setString(4, categoria);
                        pst.setInt(5, stock);
                        int i;
                        i=pst.executeUpdate();
                        if (i>0) {
                            JOptionPane.showMessageDialog(null, "Agregados con éxito...");
                            this.jTextFieldID.setText("");
                            this.jTextFieldNombre.setText("");
                            this.jTextFieldPrecio.setText("");
                            this.jComboBoxCategoria.setSelectedIndex(0);
                            this.jTextFieldStock.setText("");
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "ID ya existe\nVuelva a intentarlo...");
                        stmt = reg.prepareStatement("UPDATE tabla_juego SET stock_jue = stock_jue + 1 WHERE id ="+this.jTextFieldID.getText());
                        stmt.executeUpdate();
                        this.jTextFieldID.setText("");
                    }

                } catch (SQLException e) {
                    Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE,null,e);
                }                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro Inválido\nVuelva a Intentarlo...");

        }
    }//GEN-LAST:event_jButtonAgregar1ActionPerformed

    private void jTextFieldPrecioInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextFieldPrecioInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioInputMethodTextChanged

    private void jTextFieldPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioKeyTyped

    }//GEN-LAST:event_jTextFieldPrecioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Agregar dialog = new Agregar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar1;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldStock;
    // End of variables declaration//GEN-END:variables
}
